### ISSUE TITLE
Erro no console no front

### ISSUE THREAD

**Issue by RafaelLeone** [huogerac/djavue#10]
Estou vendo vários erros no conole! 

![Captura de tela de 2022-09-22 11-55-19](https://user-images.githubusercontent.com/80486959/191781360-e0210176-2a17-4e91-a937-2da5d691f5f3.png)

**Comment by huogerac** [comment]
@RafaelLeone acredito que atualizando algumas libs do projeto, estes erros todos estão resolvidos.
Vou deixar esta Issue ainda aberta, se conseguir testar, depois fechamos.

Valeu

**Comment by huogerac** [comment]
FYI
![Issue_10_console_errors_solved](https://user-images.githubusercontent.com/962233/199515996-c0aef74f-feba-440a-8451-dec84c5a227b.jpg)
