### ISSUE TITLE
Ao rodar vue init não configura o nome da app corretamente no django

### ISSUE THREAD

**Issue by DaniDanis** [huogerac/djavue#21]
`ModuleNotFoundError: No module named 'app1'`

Ao verificar quais modulos estavam com esse modo notei que estão vindo desde o template.

![image](https://user-images.githubusercontent.com/104365695/216351872-33bb9461-cbbc-43d6-bccf-0fca9970bd98.png)

Solução para o problema localmente, alterar tudo onde estava app1 para o nome do projeto escolhido ao rodar o comando.

vue init huogerac/djavue nome_projeto

**Comment by lukemariano** [comment]
MUITO GOD FILHO

**Comment by huogerac** [comment]
Hey @DaniDanis me diga qual a linha de comando você utilizou para criar o projeto?

```
vue init huogerac/djavue ??
```

Pq não consegui simular seu problema

Valeu

**Comment by huogerac** [comment]
@DaniDanis c tinha razão cara! Tinha um bug sim! tinha uma app1 hard coded. 
Arrumado! Tenta novamente que agora vai!

@lukemariano agora tá GOD

**Comment by huogerac** [comment]
@DaniDanis resolvido. Agora temos o repo usando cookiecutter ao invés do vue init:
https://github.com/evolutio/djavue3/
